"""Initial migration

Revision ID: 241a17a69b98
Revises: df470a57f321
Create Date: 2025-07-20 20:57:27.407748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241a17a69b98'
down_revision = 'df470a57f321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=80), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('billing_country', sa.String(length=50), nullable=False),
    sa.Column('billing_state', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caller_name', sa.String(length=80), nullable=False),
    sa.Column('call_type', sa.String(length=50), nullable=False),
    sa.Column('call_duration', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_first_name', sa.String(length=80), nullable=False),
    sa.Column('contact_last_name', sa.String(length=80), nullable=False),
    sa.Column('contact_email', sa.String(length=80), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_company', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_name', sa.String(length=80), nullable=False),
    sa.Column('account_name', sa.String(length=80), nullable=False),
    sa.Column('deal_amount', sa.Float(), nullable=False),
    sa.Column('deal_stage', sa.String(length=50), nullable=False),
    sa.Column('deal_close_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_owner', sa.String(length=80), nullable=False),
    sa.Column('lead_first_name', sa.String(length=80), nullable=False),
    sa.Column('lead_last_name', sa.String(length=80), nullable=False),
    sa.Column('lead_email', sa.String(length=80), nullable=False),
    sa.Column('lead_phone', sa.String(length=20), nullable=False),
    sa.Column('lead_source', sa.String(length=50), nullable=False),
    sa.Column('lead_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_title', sa.String(length=80), nullable=False),
    sa.Column('meeting_date', sa.DateTime(), nullable=False),
    sa.Column('meeting_time', sa.DateTime(), nullable=False),
    sa.Column('meeting_attendees', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=80), nullable=False),
    sa.Column('project_description', sa.String(length=200), nullable=False),
    sa.Column('project_status', sa.String(length=50), nullable=False),
    sa.Column('project_due_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_title', sa.String(length=80), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('report_date_from', sa.DateTime(), nullable=False),
    sa.Column('report_date_to', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=80), nullable=False),
    sa.Column('task_due_date', sa.DateTime(), nullable=False),
    sa.Column('task_status', sa.String(length=50), nullable=False),
    sa.Column('task_assignee', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('report')
    op.drop_table('project')
    op.drop_table('meeting')
    op.drop_table('lead')
    op.drop_table('deals')
    op.drop_table('contact')
    op.drop_table('calls')
    op.drop_table('account')
    # ### end Alembic commands ###
