"""Add role to User model

Revision ID: 784f33853c2d
Revises: ca5280a1e057
Create Date: 2025-07-28 23:06:47.641321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784f33853c2d'
down_revision = 'ca5280a1e057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
